
version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "Installing dependencies for test stage..."
      - pip install --upgrade pip
      - pip install -r $CODEBUILD_SRC_DIR/requirements.txt

  pre_build:
    commands:
      - echo "Verifying Python version..."
      - python --version
      - echo "Setting up Django environment..."
      - export DJANGO_SETTINGS_MODULE=restaurent.settings
      - echo "Listing files in source directory..."
      - ls -la $CODEBUILD_SRC_DIR  # Added to debug file presence
      - echo "Running pytest for test stage..."
      - pytest --maxfail=1 --disable-warnings > pytest-report.txt || echo "Pytest failed"
      - test -s pytest-report.txt
      - echo "Warning Pytest report is empty"

  build:
    commands:
      - echo "Test stage complete"

artifacts:
  files:
    - pytest-report.txt
