version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install -r requirements.txt

      - echo "Verifying Java version..."
      - java -version  # Ensures Java 11 is available

      - echo "Downloading SonarScanner 5.0.1..."
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
      - unzip sonar-scanner-cli-5.0.1.3006-linux.zip
      - export PATH=$PATH:$PWD/sonar-scanner-5.0.1.3006-linux/bin

      - echo "Downloading OWASP Dependency-Check..."
      - wget https://github.com/jeremydmiller/dependency-check/releases/download/v7.0.0/dependency-check-7.0.0-release.zip
      - unzip dependency-check-7.0.0-release.zip
      - mv dependency-check-7.0.0 /opt/dependency-check
      - export PATH=$PATH:/opt/dependency-check/bin

  pre_build:
    commands:
      - echo "Verifying Python version..."
      - python --version
      - echo "Running pylint..."
      - pylint $CODEBUILD_SRC_DIR/*.py > pylint-report-root.txt || true
      - pylint $CODEBUILD_SRC_DIR/restaurant_complaint_system/*.py > pylint-report-restaurant.txt || true
      - pylint $CODEBUILD_SRC_DIR/complaints/*.py > pylint-report-complaints.txt || true
      - cat pylint-report-root.txt pylint-report-restaurant.txt pylint-report-complaints.txt > pylint-report.txt

  build:
    commands:
      - echo "Running SonarCloud scan..."
      - sonar-scanner -X -Dsonar.login=$SONAR_TOKEN

      - echo "Running OWASP Dependency-Check..."
      - dependency-check --project "Django Project" --scan ./ --out ./dependency-check-report

  post_build:
    commands:
      - echo "Build, SonarCloud scan, and Dependency-Check completed"
      
artifacts:
  files:
    - pylint-report.txt
    - dependency-check-report/*
