version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install -r requirements.txt

      - echo "Verifying Java version..."
      - java -version  # Ensures Java 11 is available

      - echo "Downloading SonarScanner 5.0.1..."
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
      - unzip sonar-scanner-cli-5.0.1.3006-linux.zip
      - export PATH=$PATH:$PWD/sonar-scanner-5.0.1.3006-linux/bin

  pre_build:
    commands:
      - echo "Verifying Python version..."
      - python --version
      - echo "Running pylint..."
      - pylint $CODEBUILD_SRC_DIR/*.py || true
      - pylint $CODEBUILD_SRC_DIR/restaurant_complaint_system/*.py || true
      - pylint $CODEBUILD_SRC_DIR/complaints/*.py || true
      

  build:
    commands:
      - echo "Running SonarCloud scan..."
      - sonar-scanner -X -Dsonar.login=$SONAR_TOKEN

  post_build:
    commands:
      - echo "Build and scan completed"

artifacts:
  files:
    - '**/*.py'
    - pylint-report.txt

