version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing test dependencies..."
      - pip install -r $CODEBUILD_SRC_DIR/requirements.txt  # Includes pytest
  build:
    commands:
      - echo "Running pytest..."
      - pytest $CODEBUILD_SRC_DIR --verbose --junitxml=pytest-report.xml
artifacts:
  files:
    - pytest-report.xml
