version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install -r requirements.txt

      - echo "Verifying Java version..."
      - java -version  # Ensures Java 11 is available

      - echo "Downloading SonarScanner 5.0.1..."
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
      - unzip sonar-scanner-cli-5.0.1.3006-linux.zip
      - export PATH=$PATH:$PWD/sonar-scanner-5.0.1.3006-linux/bin

      - echo "Downloading OWASP Dependency-Check..."
      - wget https://github.com/dependency-check/DependencyCheck/releases/download/v12.1.0/dependency-check-12.1.0-release.zip
      - unzip dependency-check-12.1.0-release.zip
      - mv dependency-check /opt/dependency-check
      - echo "Listing contents of /opt/dependency-check..."
      - ls -la /opt/dependency-check  # Verify the move
      - echo "Listing contents of /opt/dependency-check/bin..."
      - ls -la /opt/dependency-check/bin  # Check if bin exists and contains the executable
      - chmod +x /opt/dependency-check/bin/dependency-check.sh  # Ensure executable permissions
      - export PATH=$PATH:/opt/dependency-check/bin
      - echo $PATH
      - /opt/dependency-check/bin/dependency-check.sh --version  # Test explicitly with full path

  pre_build:
    commands:
      - echo "Verifying Python version..."
      - python --version
      - echo "Running pylint..."
      - pylint $CODEBUILD_SRC_DIR/*.py > pylint-report-root.txt || true
      - pylint $CODEBUILD_SRC_DIR/restaurant_complaint_system/*.py > pylint-report-restaurant.txt || true
      - pylint $CODEBUILD_SRC_DIR/complaints/*.py > pylint-report-complaints.txt || true
      - cat pylint-report-root.txt pylint-report-restaurant.txt pylint-report-complaints.txt > pylint-report.txt

  build:
    commands:
      - echo "Running SonarCloud scan..."
      - sonar-scanner -X -Dsonar.login=$SONAR_TOKEN

      - echo "Running OWASP Dependency-Check..."
      - dependency-check.sh --project "Django Project" --scan . --out ./dependency-check-report

  post_build:
    commands:
      - echo "Build, SonarCloud scan, and Dependency-Check completed"
      
artifacts:
  files:
    - pylint-report.txt
    - dependency-check-report/*
